
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.20 at 09:15:33 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.daklan.com/xml/shoppinglistcollection", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.daklan.xml.shoppinglistcollection;
